# Generated by Django 2.2 on 2019-05-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('alarm_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Night',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.IntegerField(blank=True, null=True)),
                ('start_sleep', models.DateTimeField()),
                ('end_sleep', models.DateTimeField()),
                ('sleeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PillowUsers.User_Alarm')),
            ],
        ),
    ]
