# Generated by Django 2.2 on 2019-04-24 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PillowUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alarm_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
