# Generated by Django 2.2 on 2019-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PillowUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_alarm',
            name='alarm_time',
            field=models.TimeField(null=True),
        ),
    ]
